### ISSUE TITLE
Make entity-system a npm module

### ISSUE THREAD

**Issue by AdrianGaudebert** [AdrianGaudebert/entity-system-js#9]
So that it can be installed with, e.g., ``npm install entity-system``. That would be cool.

**Comment by AdrianGaudebert** [comment]
Making it available in bower would be super cool as well. And making it a version 1.0 while we're at it.

**Comment by AdrianGaudebert** [comment]
So all common names are taken on npm or bower, like: 

* entity
* entity-system
* entity-system-js
* ecs
* ecsjs

I'll need to find an original name for this package. ``ensyja`` (which stand for ``ENtity SYstem JAvascript`` is free, but I'm not sure that's a good name. (Note that ``ensy`` is available as well. )

@maxailloud, since you contributed to this, do you have an opinion or a better suggestion?

**Comment by maxailloud** [comment]
Maybe something like:
 * js-entity-system (a bit silly I know)
* esm-js (esm is for Entity System Model)

**Comment by AdrianGaudebert** [comment]
So I went with ``ensy`` 'cause whatever. :)

npm: https://www.npmjs.com/package/ensy
bower: http://bower.io/search/?q=ensy (though I can't see it yet, I hope it worked)

Anyone wiling to test this is very welcome! Also I guess a good test would be to update Total Madness Arena to use those packages instead of git submodules.
